version: '3.9'

services:  
  db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    volumes:
      - mssqlvolume:/mssql/data       
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express 
    ports:
      - 1433:1433      

  mq:
    image: bitnami/rabbitmq   
    restart: on-failure
    healthcheck:
        test: "exit 0" 
    ports:
      - 15672:15672
      - 5672:5672 

  # demo:
  #   build: 
  #     context: ./
  #     dockerfile: DemoDockerfile
  #   restart: always
  #   environment:      
  #     RABBIT_MQ: rabbitmq://mq:5672
  #     CONNECTION_STRING: Server=db;Database=LinhMoiInfo;User=sa;Password=Password123;
  #   command: ["dotnet", "ef", "database update"]
  #   depends_on:
  #     db:    
  #       condition: service_started      
  #     mq:
  #       condition: service_healthy
  #   ports:
  #     - 5001:80      

volumes:
  mssqlvolume: